---
name: Example 1
on:
 push:
   branches: [ main ]
jobs:
 build:
   name: Build-job
   runs-on: self-hosted
   steps:
   - name: Checkout
     uses: actions/checkout@v2
 
   - name: Deploy to k8s
     run: | 
      kubectl apply -f mysql-pv.yaml
      kubectl apply -f mysql-svc-deploy.yaml
      kubectl apply -f runner.yaml
